### ISSUE TITLE
connect function already declared

### ISSUE THREAD

**Issue by b-zee** [maidsafe/sn_api#300]
In an attempt to use the FFI from C++ I tried declaring the [`connect`](https://github.com/maidsafe/safe-api/blob/7be1a2138b36467240ab7370a2e79997739439ae/safe-ffi/ffi/mod.rs#L19) function. Doing so gives me this message:

```
/usr/include/sys/socket.h:126:12: error: conflicting declaration of C function ‘int connect(int, const sockaddr*, socklen_t)’
```

I assume it's simply because it interferes with the POSIX [`connect`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/connect.html).

Am I right to assume this should be solved in this repo by e.g. prepending all the FFI with `safe_`?

**Comment by bochaco** [comment]
That's an interesting finding, @ravinderjangra what's your take?

**Comment by m-cat** [comment]
I've pointed this out before, our FFI functions need to be namespaced or conflicts like this will occur. Prepending with the name of the library is ideal. It's one of the tasks I had listed [in this planning doc](https://hackmd.io/@5HZOdvckTSSTaM7aLUxJ-A/rJZdrOzSr#Tasks)

**Comment by ravinderjangra** [comment]
Maybe we can add the `bindgen's` code generation logic in `safe-ffi` for `C` language. That'll generate the `C` bindings, something similar to `safe_client_libs`.

**Comment by bochaco** [comment]
So you mean the bindgen would prefix them rather than prefix them in ffi code? if so, not sure if that'd be good as someone not using bindgen but only the FFI API will still have the issue?

**Comment by ravinderjangra** [comment]
I mean we can tweak the bindgen to do this instead of changing the function names and then add the generator function in `build.rs`.

**Comment by bochaco** [comment]
Right, but then anyone using the FFI directly without using bindgen will still have the issue right?

**Comment by m-cat** [comment]
Good idea @ravinderjangra, but I think @bochaco's right. For example see the explanation [here](https://docs.rs/ffi-support/0.3.5/ffi_support/fn.call_with_result.html), and all the examples [here](https://doc.rust-lang.org/nomicon/ffi.html) prepend the library name to the function name.
