### ISSUE TITLE
NRS throw error when creating names with slash

### ISSUE THREAD

**Issue by joshuef** [maidsafe/sn_api#517]
as tfa points out [over here](https://safenetforum.org/t/versions-filescontainers-cf-nrs/31448/5?u=joshuef) we should likely throw an error when creating NRS names/subnames that contain a slash in them.

**Comment by dan-da** [comment]
I'm not sure I agree.  Rather, the paths can be merged.   `safe files get` already does this, and I believe that `safe files dog` does also.  There is value to be able to have eg:

safe://subfolder --> safe://xor.../testdata/subfolder

and then load: safe://subfolder/sub2.md

The final path should be resolved as safe://xor.../testdata/subfolder/sub2.md

For more on this, see #514, #510, and #509.

Also, [rfc 0052](https://github.com/maidsafe/rfcs/blob/master/text/0052-RDF-for-public-name-resolution/0052-RDF-for-public-name-resolution.md#3-filesmap-and-path-resolution) seems to say that the paths should be merged, although the wording is a bit unclear and there is a serious lack of examples, ie:

> 3. FilesMap and Path resolution
> safe://<subName>.<publicName><path>, eg safe://pns.rfc/resolution
>
> Once the final data has been resolved, if a Files Container type of Resolvable Map has been located, then the trailing url path would be resolved from that FilesContainer, too.

**Comment by Thierry61** [comment]
> I'm not sure I agree. Rather, the paths can be merged. `safe files get` already does this, and I believe that `safe files dog` does also. There is value to be able to have eg:
> 
> safe://subfolder --> safe://xor.../testdata/subfolder
> 
> and then load: safe://subfolder/sub2.md
> 
> The final path should be resolved as safe://xor.../testdata/subfolder/sub2.md
> 

Yes we agree on this. You are talking of subfolders in the link part of an NRS entry and I find no issue with this.

But I was talking of subfolders in the name or subname part of an NRS entry. In this part the slash separator should forbidden to avoid ambiguities. Besides there is already the dot separator in this part to express hierarchies.

**Comment by dan-da** [comment]
@Thierry61 ah ok, my mistake, thx.

**Comment by iancoleman** [comment]
See #692 which resolves this.
