### ISSUE TITLE
safe vault --version shows incorrect version

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/sn_api#611]
The vault version is shown as an old version when using command `safe vault --version`.

```text
$  safe vault --version
safe-vault 0.15.0
$  safe vault update
Checking target-arch... x86_64-unknown-linux-musl
Checking current version... v0.25.1
Checking latest released version... v0.25.1
Update status: '0.25.1'!
$  safe vault --version
safe-vault 0.15.0
```

When I run baby fleming the log shows vault version as `v0.25.1`

```text
...
Running safe-vault v0.25.1
==========================
...
```

**Comment by bochaco** [comment]
The --version only applies to the CLI version, so what you see is the version of the CLI. We should try to support such thing as showing vault version and potentially also authd version, or simply throw an error when the --version is passed with any subcommand (like `vault`) as it's confusing. I've tried to fix this once but I didn't find the way as this is all provided by https://docs.rs/structopt/0.3.15/structopt, or perhaps it needs a change/fix in that crate.
