### ISSUE TITLE
Could not compile `sn_cli`, consider adding a `#![type_length_limit="2022292"]` attribute to your crate

### ISSUE THREAD

**Issue by Folaht** [maidsafe/sn_api#639]
I try compiling sn_cli. It does not compile.

https://gist.github.com/Folaht/bf64ac3bd1c04d112412b69d00e099e2#file-gistfile1-txt

## Your Environment

- `rustup show` : stable-aarch64-unknown-linux-gnu rustc 1.46.0
- `git branch --show-current` : Master
- `inxi -S` : 5.4.61-1-MANJARO-ARM aarch64

**Comment by Folaht** [comment]
Issue is occuring somewhere in shell.rs

**Comment by joshuef** [comment]
Please try against the latest version of rust. `rustup update` should get you there.

**Comment by Folaht** [comment]
rustc 1.48.0
