### ISSUE TITLE
Duplicate logic derive_secrets in sn_client

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/sn_api#714]
`pub fn derive_secrets` in sn_api

https://github.com/maidsafe/sn_api/blob/c2c6716d29e56f387776202dad94ddda9b8fe2b2/sn_api/src/api/authenticator/mod.rs#L44-L54

Essentially identical `pub fn derive_secrets` in sn_client

https://github.com/maidsafe/sn_client/blob/e6b65d62d8a42912823275c571620fd57df77552/src/utils/mod.rs#L150-L159

```rust
/// Derive Password, Keyword and PIN (in order).
pub fn derive_secrets(acc_locator: &[u8], acc_password: &[u8]) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let locator_hash = sha3_512(acc_locator);

    let pin = sha3_512(&locator_hash[SHA3_512_HASH_LEN / 2..]).to_vec();
    let keyword = locator_hash.to_vec();
    let password = sha3_512(acc_password).to_vec();

    (password, keyword, pin)
}
```

Should sn_api use the sn_client version of this function?

**Comment by bochaco** [comment]
I think the one in sn_client should be removed, this logic used to be part of sn_client but we moved all that out to be part of upper layers like authenticator API, sn_client is not aware of anything like what ew used to call accounts, or what we now have `Safe`, etc., sn_client is only aware of keypairs and signatures, upper layers are responsible for storing, retrieving and/or derivation of keypairs.

**Comment by iancoleman** [comment]
> the one in sn_client should be removed

Ok great I'll do that and undo the removal here.

I thought since sn_client would be used by both app devs + sn_api it would be the right place to have the common logic, but now you say it I can see it's not the right level of abstraction to be putting in sn_client since apps will authenticate using authd, not sn_client. Thanks for clarifying.

**Comment by iancoleman** [comment]
See https://github.com/maidsafe/sn_client/pull/1380 for fix.

**Comment by bochaco** [comment]
Yes, sn_client now became just that, a Safe client. The old so called accounts, and now called `Safe`, are an application layer abstraction, you don't really need them to connect, store and/or retrieve data, you only need valid keys and valid signatures, and that's all that sn_client now cares about. This was all part of last months' refactoring and re-structuring things.
